apiVersion: v1
kind: Pod
metadata:
  name: multi
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
      - containerPort: 80
    - name: sidecar
      image: almalinux
      command: ["sleep","200"]    